events {}

http {
  server {
    listen ${PORT:-10000};

    # Logitus testin helpottamiseksi
    access_log /dev/stdout;
    error_log /dev/stderr;

    # Välitetään kaikki pyynnöt Teslan omaan HTTPS-palveluun
    location / {
      proxy_pass https://vcp-core:14443;
      proxy_ssl_verify off;                # Teslan oma sertti, ei tarkisteta
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
